### ISSUE TITLE
제안

### ISSUE THREAD

**Issue by ysm-dev** [jybaek/hanvi#1]
알고 계실수도 있겠지만

Chrome Browser에서는 [Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)가 내장되어있습니다

Google Cloud에서 제공하는 API와 음성인식이나 음성합성과 성능이 같은지는 모르겠지만

써본결과 거의 비슷한 성능이었던것같습니다.

그래도 무료로 브라우저 내에서 demonstration 할수 있다는 점에서 좋을것같습니다 :)

멋진 프로젝트 감사합니다 👍 

- ref 
- Web Speech Recognition : [https://www.google.com/intl/en/chrome/demos/speech.html](https://www.google.com/intl/en/chrome/demos/speech.html)
- Web Speech Synthesis : [https://codepen.io/matt-west/pen/wGzuJ](https://codepen.io/matt-west/pen/wGzuJ)

**Comment by jybaek** [comment]
@ysm0622 

멋진 의견 감사합니다. :-) 
웹 브라우저를 통해 STT / TTS 가 가능하다는 것은 넌지시만 알고 있었는데 이렇게 레퍼런스를 주셨네요.

성능 테스트는 꼭 한번 해보고 싶네요. 프로젝트에 도입 여부를 떠나서 정말 좋은 정보 다시한번 감사드립니다. :-)

**Comment by ysm-dev** [comment]
이이슈는 닫겠습니다 :)
